#!/usr/bin/env node
import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = resolve(__dirname, "..");

const pkgPath = resolve(root, "package.json");
const outDir = resolve(root, "src", "generated");
const outPath = resolve(outDir, "version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));

// Major.minor come from package.json — manually managed for releases.
// Patch is derived from git commit count so every push produces a new version.
function parseMajorMinor(raw) {
  const parts = String(raw || "0.0.0").split(".").map((n) => Number.parseInt(n, 10));
  const [major, minor] = parts;
  return {
    major: Number.isFinite(major) ? major : 0,
    minor: Number.isFinite(minor) ? minor : 0,
  };
}

function tryGit(args) {
  try {
    return execSync(`git ${args}`, {
      cwd: root,
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

function commitCount() {
  // Vercel does a shallow clone by default. Unshallow first so the count is
  // accurate; ignore failures (already complete, no remote, no .git).
  tryGit("fetch --unshallow --quiet");
  const count = tryGit("rev-list --count HEAD");
  if (count && /^\d+$/.test(count)) return Number.parseInt(count, 10);
  return null;
}

function commitInfo() {
  const vercelSha = process.env.VERCEL_GIT_COMMIT_SHA;
  if (vercelSha && /^[0-9a-f]{7,40}$/i.test(vercelSha)) {
    return { commit: vercelSha.slice(0, 7), dirty: false, source: "vercel-env" };
  }
  const sha = tryGit("rev-parse --short HEAD");
  if (sha) {
    const status = tryGit("status --porcelain");
    return {
      commit: sha,
      dirty: status !== null && status.length > 0,
      source: "git",
    };
  }
  return { commit: "nogit", dirty: false, source: "fallback" };
}

const { major, minor } = parseMajorMinor(pkg.version);
const patch = commitCount();
const { commit, dirty, source } = commitInfo();

const version =
  patch !== null
    ? `${major}.${minor}.${patch}`
    : (typeof pkg.version === "string" ? pkg.version : `${major}.${minor}.0`);
const builtAt = new Date().toISOString();
const display = `v${version}+${commit}${dirty ? "-dirty" : ""}`;

const contents = `// AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerated by scripts/write-version.mjs.
// Source of truth: package.json (major.minor) + git rev-list --count HEAD (patch) + git commit (sha).

export const VERSION = ${JSON.stringify(version)};
export const COMMIT = ${JSON.stringify(commit)};
export const DIRTY = ${JSON.stringify(dirty)};
export const BUILT_AT = ${JSON.stringify(builtAt)};
export const DISPLAY_VERSION = ${JSON.stringify(display)};
`;

if (!existsSync(outDir)) {
  mkdirSync(outDir, { recursive: true });
}

let previous = "";
if (existsSync(outPath)) {
  previous = readFileSync(outPath, "utf8");
}

const previousNoTimestamp = previous.replace(/BUILT_AT = "[^"]*";/, "");
const nextNoTimestamp = contents.replace(/BUILT_AT = "[^"]*";/, "");

if (previousNoTimestamp !== nextNoTimestamp) {
  writeFileSync(outPath, contents);
  process.stdout.write(`[write-version] ${display} (patch=${patch ?? "n/a"}, sha-source=${source})\n`);
} else {
  process.stdout.write(`[write-version] up to date (${display})\n`);
}
