#!/usr/bin/env node
import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = resolve(__dirname, "..");

const args = new Set(process.argv.slice(2));
const bumpPatch = args.has("--bump-patch");

const pkgPath = resolve(root, "package.json");
const outDir = resolve(root, "src", "generated");
const outPath = resolve(outDir, "version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));

let version = typeof pkg.version === "string" ? pkg.version : "0.0.0";

if (bumpPatch) {
  const parts = version.split(".").map((n) => Number.parseInt(n, 10));
  while (parts.length < 3) parts.push(0);
  if (parts.some((n) => Number.isNaN(n))) {
    version = "0.0.1";
  } else {
    parts[2] = parts[2] + 1;
    version = `${parts[0]}.${parts[1]}.${parts[2]}`;
  }
  pkg.version = version;
  writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
}

function gitInfo() {
  try {
    const commit = execSync("git rev-parse --short HEAD", {
      cwd: root,
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
    let dirty = false;
    try {
      const status = execSync("git status --porcelain", {
        cwd: root,
        stdio: ["ignore", "pipe", "ignore"],
      })
        .toString()
        .trim();
      dirty = status.length > 0;
    } catch {
      dirty = false;
    }
    return { commit: commit || "unknown", dirty };
  } catch {
    return { commit: "nogit", dirty: false };
  }
}

const { commit, dirty } = gitInfo();
const builtAt = new Date().toISOString();
const display = `v${version}+${commit}${dirty ? "-dirty" : ""}`;

const contents = `// AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerated by scripts/write-version.mjs.
// Source of truth: package.json version + git commit.

export const VERSION = ${JSON.stringify(version)};
export const COMMIT = ${JSON.stringify(commit)};
export const DIRTY = ${JSON.stringify(dirty)};
export const BUILT_AT = ${JSON.stringify(builtAt)};
export const DISPLAY_VERSION = ${JSON.stringify(display)};
`;

if (!existsSync(outDir)) {
  mkdirSync(outDir, { recursive: true });
}

let previous = "";
if (existsSync(outPath)) {
  previous = readFileSync(outPath, "utf8");
}

const previousNoTimestamp = previous.replace(/BUILT_AT = "[^"]*";/, "");
const nextNoTimestamp = contents.replace(/BUILT_AT = "[^"]*";/, "");

if (previousNoTimestamp !== nextNoTimestamp || bumpPatch) {
  writeFileSync(outPath, contents);
  process.stdout.write(`[write-version] ${display}\n`);
} else {
  process.stdout.write(`[write-version] up to date (${display})\n`);
}
